### ISSUE TITLE
Need help on creating the underlines

### ISSUE THREAD

**Issue by EmmaJLussier** [EmmaJLussier/dealing-with-whitespace#1]
@hellachella @raven-rhea 

Hey, I'm A little stuck. How do I make The lines? cause im guessing thats where I'm supposed to put the #999 colour. I've also had some difficulty trying to fix the line length between the first paragraph(summarized by Plutrach) and the h1 how would I go about that? 
<img width="1307" alt="Screen Shot 2021-03-19 at 4 55 24 PM" src="https://user-images.githubusercontent.com/77282460/111841319-2b8c6e80-88d4-11eb-91d0-0bba153a2596.png">

**Comment by raven-rhea** [comment]
Hey Emma I would try putting a border-bottom: attribute on your header

**Comment by raven-rhea** [comment]
Another hint the first error, (Expected to see content #999) also has to do with your border-bottom

**Comment by EmmaJLussier** [comment]
Hey Raven! I just tried putting in border-bottom to my header the border hasn't shown up did I do something wrong?
