### ISSUE TITLE
Need some help with putting the summery near the h1.

### ISSUE THREAD

**Issue by EmmaJLussier** [EmmaJLussier/dealing-with-whitespace#2]
@hellachella @raven-rhea

<img width="358" alt="Screen Shot 2021-03-20 at 6 56 37 PM" src="https://user-images.githubusercontent.com/77282460/111887827-02d8a780-89ae-11eb-9a57-a8b317d367c2.png">

**Comment by raven-rhea** [comment]
Looks like you have a margin or padding on the bottom of your H1, I would try putting a margin-bottom: 0; on your h1

**Comment by EmmaJLussier** [comment]
I put my margin-bottom 0 in my h1 but it hasn't worked :(

**Comment by raven-rhea** [comment]
Hmmm try putting doing margin: 0 for your h1 and the header > p

**Comment by EmmaJLussier** [comment]
Hey I think I got it Its still a bit off what you think is different
<img width="683" alt="Screen Shot 2021-03-21 at 2 03 29 PM" src="https://user-images.githubusercontent.com/77282460/111915754-3cf98600-8a4e-11eb-9c36-fee5532be5d6.png">
?

**Comment by EmmaJLussier** [comment]
The text is a bit off How would you go about it?

**Comment by raven-rhea** [comment]
always start with the first thing in the flow that is off, so to me it looks like the space after your header > p. so try adding a small amount of margin, also the border bottom is only 1px

**Comment by raven-rhea** [comment]
Also " color: #222; " needs to be on the html

**Comment by EmmaJLussier** [comment]
Hey so I'm Just a bit off with the bottom
<img width="683" alt="Screen Shot 2021-03-21 at 2 44 46 PM" src="https://user-images.githubusercontent.com/77282460/111917038-438afc00-8a54-11eb-9d0d-fa38267c6c3d.png">

**Comment by raven-rhea** [comment]
try changing article > p margin-bottom: 1.3rem;

**Comment by EmmaJLussier** [comment]
It's super close now at 15% I think Its the bottom that is too short would that be the body or article?
<img width="432" alt="Screen Shot 2021-03-21 at 3 05 07 PM" src="https://user-images.githubusercontent.com/77282460/111917535-d6c53100-8a56-11eb-9775-043026bb001d.png">

**Comment by EmmaJLussier** [comment]
Its super close now the text is slightly
<img width="432" alt="Screen Shot 2021-03-21 at 3 11 52 PM" src="https://user-images.githubusercontent.com/77282460/111917689-c95c7680-8a57-11eb-80b2-f4860e1157bb.png">
 shifted up

**Comment by raven-rhea** [comment]
Oh man your so close, try adding a bit of margin on the bottom of your ol. Also the .quote color should be #999

**Comment by EmmaJLussier** [comment]
So the margin-bottom value i have for my ol is 1.125rem
<img width="1031" alt="Screen Shot 2021-03-21 at 3 22 52 PM" src="https://user-images.githubusercontent.com/77282460/111918021-6bc92980-8a59-11eb-9c49-2a61de9065f9.png">

**Comment by raven-rhea** [comment]
try 1.3

**Comment by EmmaJLussier** [comment]
I tried It it seems further away

**Comment by raven-rhea** [comment]
Ok try adding this 
blockquote .quote:first-child {
  margin-left: -.3em;
}

**Comment by EmmaJLussier** [comment]
Alright so I put it in I see how its closer but markbot does not
<img width="1031" alt="Screen Shot 2021-03-21 at 4 02 16 PM" src="https://user-images.githubusercontent.com/77282460/111919147-d335a800-8a5e-11eb-8c74-4f5cbcaa6ffb.png">

**Comment by raven-rhea** [comment]
K when I ran it thru on my end it worked.  maybe try re starting or re installing markbot.

**Comment by EmmaJLussier** [comment]
ok

**Comment by raven-rhea** [comment]
instead of putting your border-bottom on on the article try this 
article > p:last-child {
  padding-bottom: 1.3rem;
  border-bottom: 1px solid #999;
}

**Comment by EmmaJLussier** [comment]
Alright :) just have to reinstall markbot again so I'll be a sec

**Comment by EmmaJLussier** [comment]
Ok so I tried putting that in that the bottom is off
<img width="1031" alt="Screen Shot 2021-03-21 at 4 23 46 PM" src="https://user-images.githubusercontent.com/77282460/111919729-d7af9000-8a61-11eb-9413-bfe1d9ff544e.png">

**Comment by raven-rhea** [comment]
Ok change it to whatever is closest. All the text does seem to be slightly up, try pushing down the top paragraph by either adding a top margin to it or more bottom margin on your header maybe

**Comment by EmmaJLussier** [comment]
Oh it sort of worked to bottoms a bit too long
<img width="1031" alt="Screen Shot 2021-03-21 at 4 45 49 PM" src="https://user-images.githubusercontent.com/77282460/111920385-f95e4680-8a64-11eb-8785-e1f99a72a916.png">

**Comment by EmmaJLussier** [comment]
Ok so I did something and i'm here now im not sure what markbot has a problem with 
<img width="1031" alt="Screen Shot 2021-03-21 at 4 54 19 PM" src="https://user-images.githubusercontent.com/77282460/111920592-2fe89100-8a66-11eb-8679-1d9a5c0c4183.png">

**Comment by raven-rhea** [comment]
I just tried changing the margin-bottom: on your article > header > p to 1.3rem and the text lines up better for my markbot

**Comment by EmmaJLussier** [comment]
IT WORKED!! thank you so much raven :D

**Comment by raven-rhea** [comment]
JESUS CHRIST Hallelujah! haha
